version: '3'
services: 
  potion-catalog:
    build: ./Wharehouse
    ports: 
      - 8081:80
    container_name: potion-catalog
    environment:
      - MongoDbSettings:User=mongoadmin
      - MongoDbSettings:Password=Pass
    networks: 
      - potion-network
  sqlserver:
    image: mrfizban/msqlserver:latest
    container_name: PotionSqlServer
    ports:
      - 1434:1433
    networks:
      - potion-network
networks:
  potion-network:
    external: 
      name: potionnetwork

volumes:
  mongobdatapotion:
    driver: local
    
