version: '3'
services: 
  potion-catalog:
    build: ./Wharehouse
    ports: 
      - 8081:80
    container_name: potion-catalog
    environment:
      - MongoDbSettings:Host=potion-mongo
      - MongoDbSettings:Port=27017
      - MongoDbSettings:User=mongoadmin
      - MongoDbSettings:Password=Pass
    networks: 
      - potion-network
  potion-mongo:
    image: mongo
    container_name: potion-mongo
    ports: 
      - 27017:27017
    volumes: 
      - mongobdatapotion:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME:mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD:Pass
    networks: 
      - potion-network

networks:
  potion-network:
    external: 
      name: potionnetwork

volumes:
  mongobdatapotion:
    driver: local
    
